//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обучающейся
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Обучающейся()
        {
            this.Пользователь = new HashSet<Пользователь>();
        }
    
        public int ID_обучаещегося { get; set; }
        public string ФИО { get; set; }
        public string Учебное_заведение { get; set; }
        public string Инвалидность { get; set; }
        public string ГТО { get; set; }
        public string Тип_обучающегося { get; set; }
        public string Целевое_предприятие { get; set; }
        public string Сирота { get; set; }
        public string Категория_ВУ { get; set; }
        public Nullable<int> ID_предприятия { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователь> Пользователь { get; set; }
    }
}
