//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователь()
        {
            this.Предпочтения_обучающегося = new HashSet<Предпочтения_обучающегося>();
        }
    
        public int ID_пользователья { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int ID_обучаещегося { get; set; }
    
        public virtual Обучающейся Обучающейся { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Предпочтения_обучающегося> Предпочтения_обучающегося { get; set; }
    }
}
